#+TITLE: PhD course: Targeted Register Analysis: Exercises: Day 2 part 4

* Objectives

The learning targets of this exercise are:

- Consider the object fitted with =Ltmle=
- Investigate the fit of the nuisance parameter models (propensity score, censoring, outcome)

----------------------------------------------------------------------  

* Nuisance parameter estimators

This exercise assumes that you have succeeded with the previous
exercises today (part 1 and part 2). 

- Open the file =register_project/sandbox.R= and load the target =ltmle_fit_death_1= into
  R. The object contains useful information.
- Consider the outcome (Q) logistic regression model, the censoring logistic regression model and the
  propensity score (g) logistic regression model. The tables contain the log-odds ratios:

#+BEGIN_SRC R  :results output raw  :exports code  :session *R* :cache yes
# outcome model
ltmle_fit_death_1[[1]][[1]]$Ltmle_fit$fit$Q[[1]]
# censoring model
ltmle_fit_death_1[[1]][[1]]$Ltmle_fit$fit$g[[1]][["Censored_1"]]
# propensity score model
ltmle_fit_death_1[[1]][[1]]$Ltmle_fit$fit$g[[1]][["Drug_0"]]
#+END_SRC

- Cosmetic intervention. Note that the levels of the variables
  =agegroups=, =diabetes_duration= and =education= are not correctly
  sorted. Change that by adding the following lines (at an appropriate
  place) to the pipeline and re-running the pipeline with =tar_make()=
  (If you are unsure about where/how to do this, have a look at the
  file =secret_targets.R=).

#+ATTR_LATEX: :options otherkeywords={}, deletekeywords={}
#+BEGIN_SRC R  :results output raw  :exports code  :session *R* :cache yes  
baseline_covariates[,education:=factor(education,levels=c("Basic","Medium","High"),labels=c("Basic","Medium","High"))]
baseline_covariates[,agegroups:=factor(agegroups,levels=c("below 45","45-50","50-55","55-60","60-65","65-70","70-75","75-80","80-85","above 85"),labels=c("below 45","45-50","50-55","55-60","60-65","65-70","70-75","75-80","80-85","above 85"))]
baseline_covariates[,tertile_income:=factor(tertile_income,levels=c("Income_q1","Income_q2","Income_q3"),labels=c("Income_q1","Income_q2","Income_q3"))]
baseline_covariates[,diabetes_duration:=factor(diabetes_duration,levels=c("below 5","5-10","above 10"),labels=c(,"below 5","5-10","above 10"))]
#+END_SRC

- Review the estimated beta coefficients (log-odds ratios) of the
  nuisance parameter models regarding their sign and magnitude.
  Discuss them with your neighbor. 

- Now turn to the =Ltmle= analysis of the two year time horizon. Here
  we have 4 logistic regression models for the outcome, 3 censoring
  logistic regression models and 3 propensity score models

#+BEGIN_SRC R  :results output raw  :exports code  :session *R* :cache yes
# 4 outcome model
ltmle_fit_death_2[[1]][[1]]$Ltmle_fit$fit$Q[[1]][["Dead_4"]]
ltmle_fit_death_2[[1]][[1]]$Ltmle_fit$fit$Q[[1]][["Dead_3"]]
ltmle_fit_death_2[[1]][[1]]$Ltmle_fit$fit$Q[[1]][["Dead_2"]]
ltmle_fit_death_2[[1]][[1]]$Ltmle_fit$fit$Q[[1]][["Dead_1"]]
# 3 censoring models
ltmle_fit_death_2[[1]][[1]]$Ltmle_fit$fit$g[[1]][["Censored_3"]]
ltmle_fit_death_2[[1]][[1]]$Ltmle_fit$fit$g[[1]][["Censored_2"]]
ltmle_fit_death_2[[1]][[1]]$Ltmle_fit$fit$g[[1]][["Censored_1"]]
# 3 propensity score models
ltmle_fit_death_2[[1]][[1]]$Ltmle_fit$fit$g[[1]][["Drug_3"]]
ltmle_fit_death_2[[1]][[1]]$Ltmle_fit$fit$g[[1]][["Drug_2"]]
ltmle_fit_death_2[[1]][[1]]$Ltmle_fit$fit$g[[1]][["Drug_1"]]
ltmle_fit_death_2[[1]][[1]]$Ltmle_fit$fit$g[[1]][["Drug_0"]]
#+END_SRC  

- There are missing values for the log-odds ratios for age group
  "above 85" after time point 1. Consider and discuss what to do about
  this with your neighbor (and then do it). Possible actions are to
  reduce the population, to re-group the age variable, to change the
  formula of the nuisance parameter models.
