#+TITLE: PhD course: Targeted Register Analysis: Exercises: Day 2 part 2

* Objectives

The learning targets of this exercise are:

- to apply the function =Ltmle= in simulated register data

** Reading references  

- [[goodies/augmented_ltmle.org]] (read this!)
- https://www.jstatsoft.org/article/view/v081i01 (read in this paper if time permits)

----------------------------------------------------------------------

* Causal longitudinal data analysis

The project in the folder "register_project" contains simulated data
which are alike the data of the Danish nationwide registers. In this
exercise we apply the =Ltmle= function.

** Run Ltmle with a single time interval

We calculate the standardized 6-months mortality risks (the
probability of dying within 6-months since index date) had everyone
been randomized to take the treatment =Drug= vs not to take the treatment.

- Add the following targets to the pipeline:

#+BEGIN_SRC R  :results output raw  :exports code  :session *R* :cache yes
tar_target(ltmle_fit_death_1,
           run_Ltmle(name_outcome="Dead",
                     time_horizon=1,
                     outcome_data=survival_outcome_data,
                     regimen_data=list(Drug = regimen_data),
                     baseline_data=baseline_covariates,
                     timevar_data=time_covariates,
                     abar = list(0,1),
                     SL.library="glm",
                     verbose=TRUE)),
tar_target(table_ltmle_death_1,{
  summary(ltmle_fit_death_1)
})
#+END_SRC

- run =tar_make()= from the file =sandbox.R=
- Load the resulting table via =tar_load(table_ltmle_death_1) and interpret the results.

** Run Ltmle with 4 time intervals

We calculate the standardized 2-year mortality risks (the probability
of death within 2-years since index date) had everyone been randomized
to take treatment =Drug= continously for 2 years vs not to take the
treatment for 2 years.

- Add the following targets to the pipeline, run =tar_make()= and interprete the results.

#+BEGIN_SRC R  :results output raw  :exports code  :session *R* :cache yes
tar_target(ltmle_fit_death_2,{
  run_Ltmle(name_outcome="Dead",
            time_horizon=4,
            outcome_data=survival_outcome_data,
            regimen_data=list(Drug = regimen_data),
            baseline_data=baseline_covariates,
            timevar_data=time_covariates,
            abar = list(rep(1,4),rep(0,4)),
            SL.library="glm",
            verbose=TRUE)
}),
tar_target(table_ltmle_death_2,{
  summary(ltmle_fit_death_2)
})
#+END_SRC

- Under the causal assumptions (consistency, positivity, no unmeasured
  confounders), the standardized 2-year risks has an interpretation of
  what would have been observed had *all patients* been randomized to
  take the drug continously until the =time_horizon=, respectively,
  had all patients been randomized to not take the drug continously
  until the =time_horizon=. The output of =run_Ltmle= contains the
  standardized risks (standardized to the population of all patients,
  treated and untreated). The output also contains
  We estimate the average treatment effect (ATE) as the difference
  between the standardized risks 2-year risks and the average treatment
  ratio (Ratio) as the ratio between the standardized risks 2-year
  risks.
- Export the summary tables to the file =reports/register_report.qmd= 
- Interprete the results together with your neighbor and write the
  interpretation into the file =reports/register_report.qmd=.



